#!/bin/bash

files=$(git diff --cached --name-only --diff-filter=ACM main | grep '\.js$')

# Check for debugger statements in JavaScript files
lines=$(grep -n 'debugger;' $files)
if [ "$lines" != "" ]
then
  echo "Debugger statement found in:"
  printf "%s\n" "$lines"
  echo "These must be removed before pushing to the server."
  exit 1
fi
