coverage:
  status:
    patch:
      default: yes
      target: auto
      threshold: 0
      base: auto
      branches:
        - main
      layout: "condensed_header, condensed_files, condensed_footer"
      hide_project_coverage: TRUE
    project:
      default:
        # basic
        default: yes
        target: auto
        threshold: 0
        # advanced settings
        informational: false
        only_pulls: true

comment:                  #this is a top-level key
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false        # [true :: must have a base report to post]
  require_head: true       # [true :: must have a head report to post]
  hide_project_coverage: true # [true :: only show coverage on the git diff aka patch coverage]