coverage:
  ignore:
    - "packages/samples-lint"
    - "packages/ilib-loctool-webos-dist"
    - "scripts"
    - "packages/ilib-loctool-webos-common/test/ilib-loctool-mock"
    - "packages/ilib-loctool-webos-common/test/ilib-loctool-mock-resource"
  status:
    patch:
      default:
        target: 80
        threshold: 0.5
        if_ci_failed: ignore
    project:
      default:
        target: 80
        threshold: 0.5
        informational: false
        only_pulls: false

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
