std::string test1_label = ResBundleAdaptor::instance().getLocString("Yes");
std::string test2_label = ResBundleAdaptor::instance().getLocString("No");
std::string test3_label = ResBundleAdaptor::instance().getLocString("Update");
std::string test4_label = ResBundleAdaptor::instance().getLocString("Cancel");
std::string test5_label = ResBundleAdaptor::instance().getLocString("Programme");
std::string test6_label = ResBundleAdaptor::instance().getLocString("Sound Out");
std::string test7_label = ResBundleAdaptor::instance().getLocString("OK");
std::string test8_label = ResBundleAdaptor::instance().getLocString("* This feature is applied once and only once when the TV is turned off.");
std::string test9_label = ResBundleAdaptor::instance().getLocString("TV Information");