#!/usr/bin/env node
/*
 * convertHtml.js - converts JSON files generated by webOSJsonFormatter
 *               into HTML reports and produces an overall Total Summary page.
 *
 * Copyright (c) 2025 JEDLSoft
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import path from 'node:path';
import fs from 'fs';
import OptionsParser from 'options-parser';

// Constants
const DEFAULT_OUTPUT_DIR = './';
const TOTAL_RESULT_FILENAME = '0.total-result.html';

// Option configuration
const optionConfig = {
    files: {
        short: 'f',
        varName: 'f',
        help: 'Specify files'
    },
    directory: {
        short: 'd',
        varName: 'directory',
        help: 'Directory where JSON files are located'
    },
    outputDirectory: {
        short: 'o',
        varName: 'output folder',
        help: 'Folder where output HTML files will be generated.'
    },
    outputFileName: {
        short: 'name',
        varName: 'output file name',
        help: 'Specify output HTML file name'
    },
    errorsOnly: {
        short: 'e',
        flag: true,
        default: false,
        help: 'Only return errors and suppress warnings'
    }
};

// Parse options
const options = OptionsParser.parse(optionConfig).opt;
const errorsOnly = options.errorsOnly ?? false;
const outDir = options.outputDirectory || DEFAULT_OUTPUT_DIR;

let totalSummary = [];

// Ensure output directory exists
ensureOutputDirectory(outDir);

// Entry point
if (options.files) {
    console.log("File input is not implemented yet.");
}

if (options.directory) {
    processDirectory(options.directory);
}

/* ----------------------------------------
 * Directory Processing
 * --------------------------------------*/

function ensureOutputDirectory(directory) {
    if (!fs.existsSync(directory)) {
        fs.mkdirSync(directory, { recursive: true });
    }
}

function processDirectory(dir) {
    try {
        const stat = fs.statSync(dir);
        if (!stat.isDirectory()) throw new Error("Invalid directory");

        walkDirectory(dir);
        writeTotalSummaryResult(totalSummary);
    } catch (err) {
        console.error(`Directory error: ${err.message}`);
        process.exit(1);
    }
}

function walkDirectory(dir) {
    const files = fs.readdirSync(dir);

    for (const file of files) {
        const fullPath = path.join(dir, file);
        if (fullPath.includes(".git")) continue;

        const stat = fs.statSync(fullPath);

        if (stat.isDirectory()) {
            walkDirectory(fullPath);
        } else if (file.toLowerCase().endsWith('.json')) {
            convertToHtml(fullPath);
        }
    }
}

/* ----------------------------------------
 * HTML Summary Generation
 * --------------------------------------*/

function writeTotalSummaryResult(sumJsonData) {
    const sorted = [...sumJsonData].sort((a, b) => a.name.localeCompare(b.name));

    const html = [
        getHeader("Summary of all app results"),
        getHtmlStyle(),
        buildTotalSummaryTable(sorted),
        getFooter()
    ].join('');

    const resultPath = path.join(outDir, TOTAL_RESULT_FILENAME);
    fs.writeFileSync(resultPath, html, 'utf8');
}

function buildTotalSummaryTable(data) {
    let count = 0;
    const rows = data.map(item => {
        const ruleInfo = buildRuleInfo(item.details);

        const nameColumn =
            item.errors === 0 && item.warnings === 0
                ? item.name
                : `<a href="./${item.name}-result.html">${item.name}</a>`;

        return `
        <tr>
            <td class="highlight2">${++count}</td>
            <td class="highlight">${nameColumn}</td>
            <td class="highlight2 red">${item.errors}</td>
            <td class="highlight2 orange">${item.warnings}</td>
            <td class="highlight2">${ruleInfo}</td>
        </tr>`;
    }).join('');

    return `
<body>
<h1>Summary of all app results</h1>
<hr>
<table><thead>
<tr>
  <td class="highlight cell-bg"></td>
  <td class="highlight cell-bg">Name</td>
  <td class="highlight cell-bg">Errors</td>
  <td class="highlight cell-bg">Warnings</td>
  <td class="highlight cell-bg">Details</td>
</tr>
${rows}
</thead></table>`;
}

function buildRuleInfo(details) {
    if (!details) return '';
    return Object.entries(details)
        .map(([rule, count]) => `${rule} [ ${count} ]<br>`)
        .join('');
}

/* ----------------------------------------
 * JSON → Individual HTML Generator
 * --------------------------------------*/

function convertToHtml(jsonFile) {
    try {
        const json = JSON.parse(fs.readFileSync(jsonFile, 'utf-8'));
        const summary = createSummaryInfo(json.summary);

        if (json.summary.score !== 100) {
            summary.details = countRuleViolations(json.details);
        }

        totalSummary.push(summary);
        generateHtmlOutput(json, summary);

    } catch (err) {
        console.error(`Error in ${jsonFile}: ${err.message}`);
    }
}

function createSummaryInfo(summary) {
    return {
        name: summary.projectName,
        errors: summary.resultStats.errors,
        warnings: summary.resultStats.warnings
    };
}

function countRuleViolations(details) {
    return details.reduce((acc, cur) => {
        acc[cur.ruleName] = (acc[cur.ruleName] || 0) + 1;
        return acc;
    }, {});
}

function generateHtmlOutput(json, summaryInfo) {
    const html = [
        getHeader(`ilib-lint Result for webOS Apps`),
        getHtmlStyle(),
        getSummary(json.summary),
        getDetailResults(json.details, errorsOnly),
        getFooter()
    ].join('');

    const resultFile = options.outputFileName ||
        `${json.summary.projectName}-result.html`;

    fs.writeFileSync(path.join(outDir, resultFile), html, 'utf8');
}

/* ----------------------------------------
 * HTML Formatting Helpers
 * --------------------------------------*/

function getSummary(summary) {
    const fmt = new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 });

    const ratio = num => [
        fmt.format(num / summary.fileStats.files),
        fmt.format(num / summary.fileStats.modules),
        fmt.format(num / summary.fileStats.lines),
    ];

    const [errFile, errMod, errLine] = ratio(summary.resultStats.errors);
    const [warnFile, warnMod, warnLine] = ratio(summary.resultStats.warnings);
    const [sgFile, sgMod, sgLine] = ratio(summary.resultStats.suggestions);

    return `
<body>
<h1>[${summary.projectName}] Summary</h1><hr>
<table>
  <thead>
    <tr>
      <td></td><td>Total</td><td>${summary.fileStats.files} Files</td>
      <td>${summary.fileStats.modules} Modules</td>
      <td>${summary.fileStats.lines} Lines</td>
    </tr>
    <tr><td class="highlight">Errors:</td><td class="red">${summary.resultStats.errors}</td><td>${errFile}</td><td>${errMod}</td><td>${errLine}</td></tr>
    <tr><td class="highlight">Warnings:</td><td class="orange">${summary.resultStats.warnings}</td><td>${warnFile}</td><td>${warnMod}</td><td>${warnLine}</td></tr>
    <tr><td class="highlight">Suggestions:</td><td>${summary.resultStats.suggestions}</td><td>${sgFile}</td><td>${sgMod}</td><td>${sgLine}</td></tr>
    <tr><td class="highlight">I18N Score</td><td>${fmt.format(summary.score)}</td></tr>
  </thead>
</table><hr>`;
}

function getDetailResults(details, onlyErrors) {
    if (!Array.isArray(details) || details.length === 0) return '';

    const rows = details
        .filter(item => !onlyErrors || item.severity === 'error')
        .map(formatDetailResult)
        .join('');

    return rows ? `<div id="detail-section"><h2>Detailed Information</h2>${rows}</div>` : '';
}

function formatDetailResult(res) {
    const color =
        res.severity === 'error'
            ? 'color:white;background-color:maroon;'
            : 'color:white;background-color:orange;';

    const targetHighlighted = (res.highlight || '')
        .replace(/<e\d>/g, '<span style="color:red">')
        .replace(/<\/e\d>/g, '</span>');

    const autofix = res?.fix?.applied || 'unavailable';

    return `
<table>
<thead><tr><th colspan="2" style="${color}">[${res.severity}]</th></tr></thead>
<tbody>
  <tr><td>filepath</td><td>${res.path}</td></tr>
  <tr><td>Descriptions</td><td>${res.description}</td></tr>
  <tr><td>key</td><td>${res.key}</td></tr>
  <tr><td>source</td><td>${res.source}</td></tr>
  <tr><td>target</td><td>${targetHighlighted}</td></tr>
  <tr><td>${res.ruleName}</td><td>${res.description}</td></tr>
  <tr><td>More info</td><td><a href="${res.link}">${res.link}</a></td></tr>
  <tr><td>Auto-fix</td><td>${autofix}</td></tr>
</tbody>
</table><br>`;
}

function getHeader(title) {
    return `<!DOCTYPE html><html><head><title>${title}</title><meta charset="UTF-8"></head>`;
}

function getFooter() {
    return `</body></html>`;
}

function getHtmlStyle() {
    return `
<style>
body {
  font-family: "Segoe UI", Arial, sans-serif;
  background-color: #f7f8fa;
  color: #333;
  margin: 40px;
}
h1, h2 {
  color: #4B3AFF;
  font-weight: 700;
}
h1 {
  font-size: 32px;
  margin-bottom: 10px;
  border-left: 5px solid #4B3AFF;
  padding-left: 10px;
}
h2 {
  font-size: 26px;
  margin-top: 40px;
  margin-bottom: 15px;
}
.summary, .detail {
  background: #fff;
  border-radius: 10px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  padding: 25px;
  margin-bottom: 30px;
}
table {
  width: 90%;
  border-collapse: collapse;
  margin-top: 10px;
}
th, td {
  padding: 10px 12px;
  text-align: left;
  border-bottom: 1px solid #e0e0e0;
}
th {
  background-color: #6b1b1b;
  color: white;
  font-size: 18px;
}
tr:hover td {
  background-color: #f3f3f3;
}
.highlight {
  font-weight: bold;
  font-size: 20px;
}
.highlight2 {
  font-weight: bold;
  font-size: 18px;
}
.green {
  color: #2e8b57;
  font-weight: bold;
}
.red {
  color: #d9534f;
  font-weight: bold;
}
.orange {
  color: #f0ad4e;
  font-weight: bold;
}
.cell-bg {
  background-color: #91b9e3ff;
}
a {
  color: #4B3AFF;
  text-decoration: none;
}
a:hover {
  text-decoration: underline;
}
hr {
  border: none;
  border-top: 2px solid #ddd;
  margin: 30px 0;
  width: 90%;
}
</style>
`;
}