name: CodeCov

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ilib-loctool-webos-javascript] # 각 패키지 이름을 나열합니다.
        node-version: [20]

    steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  # workaround for `git error: fatal: bad object` when using `--affected`:
                  # ensure PR base commit is fetched
                  # per https://stackoverflow.com/a/78153130
                  fetch-depth: $(( ${{ github.event.pull_request.commits }} + 1 ))
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Install Chrome
              uses: browser-actions/setup-chrome@v1
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Affected packages test and coverage
              run: pnpm coverage
              env:
                  # temporary workaround for `Failed to resolve base ref 'main' from GitHub Actions event`:
                  # manually set PR base commit ref
                  # per https://github.com/vercel/turborepo/issues/9320#issuecomment-2499219314
                  TURBO_SCM_BASE: ${{ github.event.pull_request.base.sha }}
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                 token: ${{ secrets.CODECOV_TOKEN }}

