name: Test All

on:
    push:
        branches:
            - main

jobs:
    test-all:
        name: Test All
        uses: ./.github/workflows/_test-common.yml
        with:
            test-command: pnpm test:ci
            coverage-command: pnpm coverage
            run-script-tests: true
        secrets:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}