name: Test All

on:
    push:
        branches:
            - main

jobs:
    test-all:
        name: Test All
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Install Chrome
              uses: browser-actions/setup-chrome@v1
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run tests
              run: pnpm test:ci
            - name: Run Codecov
              run: pnpm coverage
              env:
                  # temporary workaround for `Failed to resolve base ref 'main' from GitHub Actions event`:
                  # manually set PR base commit ref
                  # per https://github.com/vercel/turborepo/issues/9320#issuecomment-2499219314
                  TURBO_SCM_BASE: ${{ github.event.pull_request.base.sha }}
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}