name: Test Affected

on: [push, pull_request]

jobs:
    test-affected:
        name: Test Affected
        uses: ./.github/workflows/_test-common.yml
        with:
            # workaround for `git error: fatal: bad object` when using `--affected`:
            # ensure PR base commit is fetched
            # per https://stackoverflow.com/a/78153130
            fetch-depth: $(( ${{ github.event.pull_request.commits }} + 1 ))
            test-command: pnpm test:ci
            run-script-tests: true
            # temporary workaround for `Failed to resolve base ref 'main' from GitHub Actions event`:
            # manually set PR base commit ref
            # per https://github.com/vercel/turborepo/issues/9320#issuecomment-2499219314
            turbo-scm-base: ${{ github.event.pull_request.base.sha }}
        secrets:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}